# 넘파이 Numpy

## numpy as np

In [1]:
# numpy
import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]

In [3]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1 , arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [5]:
arr1.shape , arr1.dtype

((5,), dtype('int64'))

In [6]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3.shape , arr3.dtype

((2, 3), dtype('int64'))

In [11]:
zz = np.zeros(10)
zz, zz.shape , zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [13]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [14]:
oo = np.ones(7)
oo , oo.shape , oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [15]:
ooo = np.ones((2,10))
ooo, ooo.shape, ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [18]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [20]:
print(arr1.shape , arr1.dtype)
print(arr2.shape , arr2.dtype)

(2, 3) int64
(2, 3) int64


In [29]:
result0 = arr1*3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10
result4 = arr1 * arr2
result5 = arr1 / arr2
print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

# 브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])
print(arr1 + arr3)
print(arr1 * arr3)

[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[23 35 47]
 [26 38 50]]
[[ 22  66 132]
 [ 88 165 264]]


## 1차원

In [32]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수
arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim


(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [33]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype='str')
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [49]:
arr4 = np.full((4,3),"없어요")
arr4
arr5 = np.eye(3)
arr5
arr6 = np.linspace(0,100,5, endpoint=False, dtype="int64")
print(arr6)
arr7 = np.arange(0,100,20)
print(arr7)

[ 0 20 40 60 80]
[ 0 20 40 60 80]


## 2차원

In [55]:
arr20 = np.array([[1,2],[3,4]])
arr20 , arr20.shape, arr20.size, arr20.dtype, arr20.ndim, type(arr20)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [ ]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21 , arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22 , arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23 , arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요:",e)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>


## 인덱싱(마스크)

In [27]:
import numpy as np
# 난수 발생
ran_data = np.random.randn(8,4)
ran_data

array([[-1.10036899, -0.47984469, -0.29723042, -0.67975541],
       [-1.72536304,  0.6730523 ,  0.36691006,  0.77661832],
       [ 0.47015647,  1.27685522,  0.44479618,  0.56916723],
       [ 1.21969542, -0.59575631, -0.27750731,  0.25237978],
       [ 0.00898787, -1.50421826,  0.32552307,  1.87211828],
       [ 1.84307556, -0.51583449,  1.57788069,  1.34483687],
       [ 0.62471983,  0.74613366, -0.4281873 , -2.88260375],
       [-0.17906418, -0.13081855,  0.47949155, -0.4308686 ]])

In [5]:
mask = np.array([True,False,True,False,False,True,True,False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [6]:
ran_data[mask]

array([[-0.81965086, -1.16400345,  1.24708891,  0.73006793],
       [ 1.18101555,  1.24728693,  0.91615574, -1.78745878],
       [ 1.01978673,  0.81535496, -0.03354386,  1.5391312 ],
       [-0.40890042,  0.91627458, -0.84338704, -0.88253335]])

In [7]:
fruit = np.array(['apple','banana','apple','kiwi','orange','apple','apple','melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [ ]:
fruit_mask = (fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [9]:
ran_data[fruit_mask]

array([[-0.81965086, -1.16400345,  1.24708891,  0.73006793],
       [ 1.18101555,  1.24728693,  0.91615574, -1.78745878],
       [ 1.01978673,  0.81535496, -0.03354386,  1.5391312 ],
       [-0.40890042,  0.91627458, -0.84338704, -0.88253335]])

In [14]:
ran_data[(fruit == 'apple')|(fruit=='orange'),1:-1] # ran_data[행,열]

array([[-1.16400345,  1.24708891],
       [ 1.24728693,  0.91615574],
       [ 1.79813667,  0.33361945],
       [ 0.81535496, -0.03354386],
       [ 0.91627458, -0.84338704]])

## 인덱스와 마스크의 응용

In [19]:
ran_data[:,0] > 0

array([False,  True,  True, False,  True,  True, False,  True])

In [17]:
ran_data[ran_data[:,:] > 0]

array([1.24708891, 0.73006793, 0.62109092, 1.44063012, 0.44276807,
       1.18101555, 1.24728693, 0.91615574, 0.5801626 , 0.2048928 ,
       1.79813667, 0.33361945, 1.63094941, 1.01978673, 0.81535496,
       1.5391312 , 0.91627458, 1.33511235, 1.02007908, 0.99575708])

In [ ]:
ran_data = np.random.randn(8,4)
ran_data[ran_data[:,0] < 0,2:4] = np.nan # np.nan
ran_data

array([[ 0.15427161,  0.79037287,  0.36238213,  0.20624937],
       [-0.59419344,  0.7784205 ,         nan,         nan],
       [ 1.07749052,  0.10393255,  0.2531623 , -0.03831084],
       [ 0.70062999, -0.06253658,  2.75628643,  2.43931314],
       [-1.81352809, -0.34506369,         nan,         nan],
       [ 0.70049522,  1.01468878,  0.43978665, -0.18130708],
       [ 1.10235694, -0.25142297,  1.93707893, -0.23821794],
       [-0.06919136, -1.30680053,         nan,         nan]])

In [48]:
fix_data = ran_data[~np.isnan(ran_data).any(axis=1)]
fix_data

array([[ 0.15427161,  0.79037287,  0.36238213,  0.20624937],
       [ 1.07749052,  0.10393255,  0.2531623 , -0.03831084],
       [ 0.70062999, -0.06253658,  2.75628643,  2.43931314],
       [ 0.70049522,  1.01468878,  0.43978665, -0.18130708],
       [ 1.10235694, -0.25142297,  1.93707893, -0.23821794]])

In [49]:
fix_data2 = np.abs(fix_data)
fix_data2

array([[0.15427161, 0.79037287, 0.36238213, 0.20624937],
       [1.07749052, 0.10393255, 0.2531623 , 0.03831084],
       [0.70062999, 0.06253658, 2.75628643, 2.43931314],
       [0.70049522, 1.01468878, 0.43978665, 0.18130708],
       [1.10235694, 0.25142297, 1.93707893, 0.23821794]])

In [51]:
fix_data3 = np.sqrt(fix_data2)
fix_data3

array([[0.39277424, 0.88902917, 0.60198184, 0.45414686],
       [1.03802241, 0.32238572, 0.50315236, 0.19573156],
       [0.83703643, 0.25007314, 1.66020674, 1.56183006],
       [0.83695593, 1.00731762, 0.66316412, 0.42580169],
       [1.04993187, 0.50142095, 1.39178983, 0.48807575]])

In [52]:
fix_data4 = np.log(fix_data3)
fix_data4

array([[-0.93452028, -0.11762523, -0.50752801, -0.78933465],
       [ 0.03731737, -1.13200657, -0.68686226, -1.63101115],
       [-0.17788768, -1.38600183,  0.50694214,  0.44585825],
       [-0.17798387,  0.00729097, -0.41073277, -0.85378156],
       [ 0.04872528, -0.69030932,  0.33059057, -0.71728467]])

In [53]:
np.sign(fix_data4)

array([[-1., -1., -1., -1.],
       [ 1., -1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [-1.,  1., -1., -1.],
       [ 1., -1.,  1., -1.]])

In [ ]:
# 삼각함수 값을 계산하기( cos, cosh, sin, sinh, tan ,tanh)
np.cos(fix_data4)

array([[ 0.59420434,  0.99309013,  0.87394861,  0.7043178 ],
       [ 0.99930379,  0.42484418,  0.77323951, -0.06017844],
       [ 0.98421966,  0.18374453,  0.8742332 ,  0.90224089],
       [ 0.98420264,  0.99997342,  0.91682849,  0.65713742],
       [ 0.99881316,  0.77104909,  0.94585081,  0.75359341]])

In [56]:
# 두개의 array에 동일한 위치의 요소끼리 비교 하기
data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1 , data2

(array([[-0.55633187,  0.74791827, -1.19080401,  0.40776312],
        [ 1.09086363,  0.86435815, -0.73387872, -1.23698562],
        [-0.26791823, -1.41034036,  0.13826559,  0.75036394],
        [ 0.79379881, -0.59476663, -0.55244041, -0.42110269],
        [-0.41671936,  0.36338179, -0.69917686,  0.60225997],
        [-0.23100644,  1.29928938, -0.0957612 ,  0.21032676],
        [-0.63305023, -0.1591616 ,  1.67392468, -0.62972987],
        [-0.19590336,  0.88052093,  0.06187663,  0.03443025]]),
 array([[ 1.35235605,  1.31350195,  0.06755911, -0.62139635],
        [ 2.20774317,  0.95606041, -2.10926353,  0.43851148],
        [-1.01406035,  1.02837767,  1.24620625, -1.77759542],
        [-0.60695995, -0.60069358, -0.53756333, -1.39626392],
        [-0.82977278, -1.91771243, -1.13799902, -0.06799576],
        [-1.38642152,  0.58559799,  1.36315397,  4.03724767],
        [-0.71645021,  1.43897139,  1.91600307, -0.51231061],
        [-0.41682414, -0.73147689,  0.98206674,  0.10515941]]))

In [ ]:
np.maximum(data1, data2) 

array([[ 1.35235605,  1.31350195,  0.06755911,  0.40776312],
       [ 2.20774317,  0.95606041, -0.73387872,  0.43851148],
       [-0.26791823,  1.02837767,  1.24620625,  0.75036394],
       [ 0.79379881, -0.59476663, -0.53756333, -0.42110269],
       [-0.41671936,  0.36338179, -0.69917686,  0.60225997],
       [-0.23100644,  1.29928938,  1.36315397,  4.03724767],
       [-0.63305023,  1.43897139,  1.91600307, -0.51231061],
       [-0.19590336,  0.88052093,  0.98206674,  0.10515941]])

In [58]:
np.minimum(data1, data2) 

array([[-0.55633187,  0.74791827, -1.19080401, -0.62139635],
       [ 1.09086363,  0.86435815, -2.10926353, -1.23698562],
       [-1.01406035, -1.41034036,  0.13826559, -1.77759542],
       [-0.60695995, -0.60069358, -0.55244041, -1.39626392],
       [-0.82977278, -1.91771243, -1.13799902, -0.06799576],
       [-1.38642152,  0.58559799, -0.0957612 ,  0.21032676],
       [-0.71645021, -0.1591616 ,  1.67392468, -0.62972987],
       [-0.41682414, -0.73147689,  0.06187663,  0.03443025]])

In [ ]:
np.maximum(data1 , 0) # ReLU(x) 같다.

array([[0.        , 0.74791827, 0.        , 0.40776312],
       [1.09086363, 0.86435815, 0.        , 0.        ],
       [0.        , 0.        , 0.13826559, 0.75036394],
       [0.79379881, 0.        , 0.        , 0.        ],
       [0.        , 0.36338179, 0.        , 0.60225997],
       [0.        , 1.29928938, 0.        , 0.21032676],
       [0.        , 0.        , 1.67392468, 0.        ],
       [0.        , 0.88052093, 0.06187663, 0.03443025]])

In [60]:
np.minimum(np.maximum(data2,0.5),1.7)

array([[1.35235605, 1.31350195, 0.5       , 0.5       ],
       [1.7       , 0.95606041, 0.5       , 0.5       ],
       [0.5       , 1.02837767, 1.24620625, 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.58559799, 1.36315397, 1.7       ],
       [0.5       , 1.43897139, 1.7       , 0.5       ],
       [0.5       , 0.5       , 0.98206674, 0.5       ]])

## 통계함수

In [64]:
data = np.random.randn(4,4)
data

array([[ 0.54765262, -0.75789711, -0.99014159, -1.57717306],
       [ 1.55486832,  0.11026469,  1.23265241,  0.05354986],
       [ 1.3352004 , -1.6881581 ,  2.75670631, -0.04443442],
       [-0.47256041,  1.54276002,  0.84243619,  0.19029129]])

In [67]:
np.sum(data, axis=0)

array([ 2.96516093, -0.79303049,  3.84165333, -1.37776632])

In [66]:
np.sum(data, axis=1)

array([-2.77755913,  2.95133528,  2.3593142 ,  2.1029271 ])

In [69]:
np.sum(data[:,1:3], axis=1)

array([-1.7480387 ,  1.3429171 ,  1.06854821,  2.38519621])

In [70]:
data2 = np.random.randn(3,5)
data2

array([[-0.09384416,  2.11569558, -1.99184355, -1.87940784,  0.03180848],
       [-0.53681739,  0.02964502,  0.23303013, -0.43134626,  1.85531382],
       [-0.96684797, -0.3188881 ,  0.00905986,  0.55405247,  0.30263381]])

In [ ]:
# 요소의 평균구하기
np.mean(data2)

np.float64(-0.07251707444047077)

In [72]:
np.mean(data2, axis=0)

array([-0.53250318,  0.6088175 , -0.58325119, -0.58556721,  0.7299187 ])

In [73]:
np.mean(data2, axis=1)

array([-0.3635183 ,  0.22996506, -0.08399799])

In [ ]:
# 요소의 가장 작은 값 구하기, 반대는 max
np.min(data2, axis=1) 

array([-1.99184355, -0.53681739, -0.96684797])

In [ ]:
# 표준편차 계산
np.std(data2)

np.float64(1.0743510217757972)

In [ ]:
# 분산계산
np.var(data2)

np.float64(1.1542301179906997)