# 판다스 (pandas)

In [3]:
# !pip install pandas

In [4]:
import numpy as np
import pandas as pd

In [11]:
# 판다스 Series
data1 = np.arange(1,6)
print(data1)
data2 = pd.Series(data1)
print(data2)
data2.index , data2.values

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


(RangeIndex(start=0, stop=5, step=1), array([1, 2, 3, 4, 5]))

In [12]:
data3 = pd.Series([11,22,33,44,55])
data3

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [13]:
dd = {"apple":4400,"banana":3500,"kiwi":2200,"orange":1700,"mango":8800}
data4 = pd.Series(dd)
data4

apple     4400
banana    3500
kiwi      2200
orange    1700
mango     8800
dtype: int64

In [25]:
print(type(data4))
data4.name = "과일가격표"
data4.index.name = "과일이름"
data4 , data4.index , data4.values

<class 'pandas.core.series.Series'>


(과일이름
 apple     4400
 banana    3500
 kiwi      2200
 orange    1700
 mango     8800
 Name: 과일가격표, dtype: int64,
 Index(['apple', 'banana', 'kiwi', 'orange', 'mango'], dtype='object', name='과일이름'),
 array([4400, 3500, 2200, 1700, 8800]))

In [26]:
data2.index = ["aa","bb","cc","dd","ee"] # 개수가 같아야 함
data2 , data2.index, data2.values

(aa    1
 bb    2
 cc    3
 dd    4
 ee    5
 dtype: int64,
 Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object'),
 array([1, 2, 3, 4, 5]))

In [35]:
# 판다스 시리즈 데이터 타입 설정, 인덱스 수정
data5 = pd.Series(np.arange(1,7), dtype="float", index=["aa","bb","cc","dd","ee","ff"] )
data5 , data5.shape, data5.size, data5.ndim

(aa    1.0
 bb    2.0
 cc    3.0
 dd    4.0
 ee    5.0
 ff    6.0
 dtype: float64,
 (6,),
 6,
 1)

In [44]:
# 시리즈 원소에 접근방법
print(data5)
print("data5['dd']:",data5['dd']) # deprecated
print("data5.loc['dd']:",data5.loc['dd'])
print("data5[3]:",data5[3]) # deprecated
print("data5.iloc[3]:",data5.iloc[3])

aa    1.0
bb    2.0
cc    3.0
dd    4.0
ee    5.0
ff    6.0
dtype: float64
data5['dd']: 4.0
data5.loc['dd']: 4.0
data5[3]: 4.0
data5.iloc[3]: 4.0


C:\Users\user\AppData\Local\Temp\ipykernel_19564\901892072.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("data5[3]:",data5[3]) # deprecated


## 데이터프레임 Dataframe

In [48]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["a","b","c"],columns=["A","B","C"])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [49]:
num = np.arange(1,10).reshape(3,3)
df = pd.DataFrame(num,index=["a","b","c"],columns=["A","B","C"])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [56]:
dd = {"과일이름":["apple","banana","kiwi","melon","orange","mango"],
      "가격":[4400,5000,2500,7000,2000,8800],
      "개수":[3,8,11,22,6,5]}
df2 = pd.DataFrame(dd)
df2.index = range(1,7)
df2.index.name = "No."
df2 , df2.columns, df2.values

(       과일이름    가격  개수
 No.                  
 1     apple  4400   3
 2    banana  5000   8
 3      kiwi  2500  11
 4     melon  7000  22
 5    orange  2000   6
 6     mango  8800   5,
 Index(['과일이름', '가격', '개수'], dtype='object'),
 array([['apple', 4400, 3],
        ['banana', 5000, 8],
        ['kiwi', 2500, 11],
        ['melon', 7000, 22],
        ['orange', 2000, 6],
        ['mango', 8800, 5]], dtype=object))

In [57]:
df2

과일이름    가격  개수
No.                  
1     apple  4400   3
2    banana  5000   8
3      kiwi  2500  11
4     melon  7000  22
5    orange  2000   6
6     mango  8800   5

In [ ]:
df2.columns.name = "info"
df2.index.name =''
df2.columns = ['과일이름','원가','수량',]
df2

과일이름    원가  수량
                   
1   apple  4400   3
2  banana  5000   8
3    kiwi  2500  11
4   melon  7000  22
5  orange  2000   6
6   mango  8800   5

In [67]:
df2.describe()

원가         수량
count     6.000000   6.000000
mean   4950.000000   9.166667
std    2609.022806   6.853223
min    2000.000000   3.000000
25%    2975.000000   5.250000
50%    4700.000000   7.000000
75%    6500.000000  10.250000
max    8800.000000  22.000000

In [74]:
df3 = pd.DataFrame(df2, columns = ['과일이름','품종','원가','할인','수량','합계'])
df3


과일이름  품종    원가  할인  수량  합계
                               
1   apple NaN  4400 NaN   3 NaN
2  banana NaN  5000 NaN   8 NaN
3    kiwi NaN  2500 NaN  11 NaN
4   melon NaN  7000 NaN  22 NaN
5  orange NaN  2000 NaN   6 NaN
6   mango NaN  8800 NaN   5 NaN

In [76]:
df3.loc[:,'품종'] = df3.loc[:,'품종'].astype('object')
df3.loc[:,'품종'] = ['신선한','궁금한','맛있는','최적의','웰빙','유기농']
df3.loc[:,'할인'] = [0.2,0.3,0.2,0.1,0.2,0.3]
df3

과일이름   품종    원가   할인  수량  합계
                                 
1   apple  신선한  4400  0.2   3 NaN
2  banana  궁금한  5000  0.3   8 NaN
3    kiwi  맛있는  2500  0.2  11 NaN
4   melon  최적의  7000  0.1  22 NaN
5  orange   웰빙  2000  0.2   6 NaN
6   mango  유기농  8800  0.3   5 NaN